### PR TITLE
Technical Events Part 1

### LINKED ISSUE #71: Redirection to SLAC website for SLAC 2020 registration
Under the sub-part of the website dealing with the registration for SLAC, please ensure the link redirects to the registration page of SLAC 2020 (https://slac.faceaseb.com/#pricing).
Also, please ensure you enter the following details for registration:
1. Teams of 3 or 4 allowed only.
2. Individual participation is allowed, but will not be eligible for prizes and judgements.

### PR DESCRIPTION
**Pull request by Ashwin-Ganti**
Signed-off-by: Ashwin-Ganti <gantiashwin6@gmail.com>
Fixes #71 
#70

## Contains webpages for technical events

### CODE REVIEW

**Review by aravindvnair99 — CHANGES_REQUESTED** [review]
@Ashwin-Ganti Please resize and compress the images. That's too big for web usage.

**Review by suneel87 — APPROVED** [review]

**Comment by suneel87** [comment]
@aravindvnair99 @VinayakTekade @Ashwin-Ganti The images have been compressed. I've added routes, luckily GitHub says there aren't any merge conflicts, made a few changes here and there, and the pages look fine

**Comment by suneel87** [comment]
One more thing, the font and style of text across all three types of events are non-uniform, I've added some CSS classes to my management branch, and uhhhhh, we can take care of all that after merging has been done.

**Review by VinayakTekade — APPROVED** [review]
`eventRegTemplate` is style classes are broken. Will fix it in #79

**Pull request merged**
