### PR TITLE
Added Landing Image

### PR DESCRIPTION
**Pull request by Subaharish**
Signed-off-by: Subaharish <subaharish2001@gmail.com>

Made the Landing Page
Added Landing Page
Removed unwanted code

### CODE REVIEW

**Review by aravindvnair99 — CHANGES_REQUESTED** [review]
@Subaharish  8 - 10 MB is too big a file size. Please compress and resize the images for web usage before uploading. A few references:

- [Images | Web Fundamentals | Google Developers](https://developers.google.com/web/fundamentals/design-and-ux/responsive/images)
- https://www.foregroundweb.com/image-size

**Comment by aravindvnair99** [comment]
> @Subaharish 8 - 10 MB is too big a file size. Please compress and resize the images for web usage before uploading. A few references:
> 
> * [Images | Web Fundamentals | Google Developers](https://developers.google.com/web/fundamentals/design-and-ux/responsive/images)
> * https://www.foregroundweb.com/image-size

@Subaharish This is still pending. Please do go through the links.

**Comment by Subaharish** [comment]
> > @Subaharish 8 - 10 MB is too big a file size. Please compress and resize the images for web usage before uploading. A few references:
> > 
> > * [Images | Web Fundamentals | Google Developers](https://developers.google.com/web/fundamentals/design-and-ux/responsive/images)
> > * https://www.foregroundweb.com/image-size
> 
> @Subaharish This is still pending. Please do go through the links.

@aravindvnair99  Check now

**Comment by aravindvnair99** [comment]
> > > @Subaharish 8 - 10 MB is too big a file size. Please compress and resize the images for web usage before uploading. A few references:
> > > 
> > > * [Images | Web Fundamentals | Google Developers](https://developers.google.com/web/fundamentals/design-and-ux/responsive/images)
> > > * https://www.foregroundweb.com/image-size
> > 
> > 
> > @Subaharish This is still pending. Please do go through the links.
> 
> @aravindvnair99 Check now

@Subaharish I still see 2 and 10 MB. You need to alter the actual size of the images. Not tweak with CSS. The browser still has to download that much and then apply CSS.

**Review by aravindvnair99 — APPROVED** [review]
Merging for the time being.

**Pull request merged**
