### PR TITLE
Cultural2

### LINKED ISSUE #70: Posters for event list
- [ ] Update the event list with posters

### PR DESCRIPTION
**Pull request by PriyaaIyer**
#70 

- Added Art Gallery Page.
- Added Best Foot Forward Page. 
- Added Conquer The Squares Page. 
- Added Open Mic - Comedy Page. 
- Added Shipwreck Page. 
- Added Open Mic - Music Page. 
- Added Battle Of The Bands Page. 
- Added Open Mic - Talk On A Topic Page. 
- Added routes to corresponding pages.
- Added posters to each pages.

Proposed Changes
- Need to optimize for mobile view.

### CODE REVIEW

**Comment by PriyaaIyer** [comment]
@aravindvnair99 @VinayakTekade Cultural Events is done.

**Comment by VinayakTekade** [comment]
@PriyaaIyer The posters are still pending. Adding this PR to draft.

**Review by suneel87 — APPROVED** [review]

**Review by aravindvnair99 — CHANGES_REQUESTED** [review]
@PriyaaIyer The images also need to be added as @VinayakTekade rightly pointed out. Make sure you add them after resizing and compressing, as necessary.

**Comment by VinayakTekade** [comment]
@PriyaaIyer What's the status on Posters?

**Review by VinayakTekade — APPROVED** [review]

**Pull request merged**
