### PR TITLE
added contents of about page

### PR DESCRIPTION
**Pull request by PriyaaIyer**
Signed-off-by: Priyaa Iyer <rgpriyaa20@gmail.com>

#11 
 
contents added
 and few images added

### CODE REVIEW

**Review by aravindvnair99 — CHANGES_REQUESTED** [review]
@PriyaaIyer 8 - 10 MB is too big a file size. Please compress and resize the images for web usage before uploading. A few references:

- [Images | Web Fundamentals | Google Developers](https://developers.google.com/web/fundamentals/design-and-ux/responsive/images)
- https://www.foregroundweb.com/image-size

**Comment by aravindvnair99** [comment]
> @PriyaaIyer 8 - 10 MB is too big a file size. Please compress and resize the images for web usage before uploading. A few references:
> 
> * [Images | Web Fundamentals | Google Developers](https://developers.google.com/web/fundamentals/design-and-ux/responsive/images)
> * https://www.foregroundweb.com/image-size

@PriyaaIyer This is still pending. Please do go through the links.

**Comment by PriyaaIyer** [comment]
> > @PriyaaIyer 8 - 10 MB is too big a file size. Please compress and resize the images for web usage before uploading. A few references:
> > 
> > * [Images | Web Fundamentals | Google Developers](https://developers.google.com/web/fundamentals/design-and-ux/responsive/images)
> > * https://www.foregroundweb.com/image-size
> 
> @PriyaaIyer This is still pending. Please do go through the links.

@aravindvnair99 issue fixed.

**Comment by aravindvnair99** [comment]
> > > @PriyaaIyer 8 - 10 MB is too big a file size. Please compress and resize the images for web usage before uploading. A few references:
> > > 
> > > * [Images | Web Fundamentals | Google Developers](https://developers.google.com/web/fundamentals/design-and-ux/responsive/images)
> > > * https://www.foregroundweb.com/image-size
> > 
> > 
> > @PriyaaIyer This is still pending. Please do go through the links.
> 
> @aravindvnair99 issue fixed.

@PriyaaIyer Yes, it's smaller now. Is that the best possible compression though? I feel that can be reduced even further. Ideally, we want it in KBs so that pages load faster.

**Review by aravindvnair99 — DISMISSED** [review]
@PriyaaIyer I've fixed a few things. Have a look at these for next time:

- [8 Tips for Dark Theme Design](https://uxplanet.org/8-tips-for-dark-theme-design-8dfc2f8f7ab6)
- [Dark theme - Material Design](https://material.io/design/color/dark-theme.html)
- [Dark UIs. The Good and the Bad. Dos and Don’ts.](https://www.toptal.com/designers/ui/dark-ui)

**Review by aravindvnair99 — APPROVED** [review]

**Pull request merged**
