### PR TITLE
Optimized Landing Page

### PR DESCRIPTION
**Pull request by Subaharish**
Fixes #
Added Countdown 
Responsive Countdown

### CODE REVIEW

**Comment by VinayakTekade** [comment]
@Subaharish Compress and resize all the images above size 1MB, avoid 4K resolution and 1080p should be fine.

**Review by VinayakTekade — CHANGES_REQUESTED** [review]
@Subaharish Compress and resize all the images above size 1MB. Avoid 4K resolution, 1080p should be fine.

**Comment by Subaharish** [comment]
> @Subaharish Compress and resize all the images above size 1MB. Avoid 4K resolution, 1080p should be fine. Also, make sure the extension is `jpg` instead of `JPG`.

@VinayakTekade resized all images

**Comment by VinayakTekade** [comment]
> > @Subaharish Compress and resize all the images above size 1MB. Avoid 4K resolution, 1080p should be fine. Also, make sure the extension is `jpg` instead of `JPG`.
> 
> @VinayakTekade resized all images

Also, change the extension

**Comment by Subaharish** [comment]
> > > @Subaharish Compress and resize all the images above size 1MB. Avoid 4K resolution, 1080p should be fine. Also, make sure the extension is `jpg` instead of `JPG`.
> > 
> > 
> > @VinayakTekade resized all images
> 
> Also, change the extension

@VinayakTekade  Changed extension from JPG to jpg

**Review by VinayakTekade — DISMISSED** [review]

**Pull request merged**
