### PR TITLE
Logo reveal

### LINKED ISSUE #10: Landing Page
## Requirements to be fulfilled 
- [x] Hamburger without navbar
- [x] Countdown for logo reveal
- [x] Logo reveal on countdown

### Stage 2
- [x] Timer Syle 
- [x] Test with Logo
- [x] Stars Animation
- [x] Test Background and font colors

### PR DESCRIPTION
**Pull request by Subaharish**
Signed-off-by: Subaharish <48942935+Subaharish@users.noreply.github.com>

Fixes #10 
Logo reveal after countdown goes null
Added star animation on the background
Changed timer style
Updated Background gradient

Proposed Changes:
- logo reveal div is not in center.
- color scheme change is still there.

### CODE REVIEW

**Comment by VinayakTekade** [comment]
#10

**Comment by Subaharish** [comment]
@VinayakTekade  Fix the code factor issue

**Comment by VinayakTekade** [comment]
> @VinayakTekade Fix the code factor issue

Okay

**Review by VinayakTekade — APPROVED** [review]

**Review by aravindvnair99 — CHANGES_REQUESTED** [review]
@Subaharish @VinayakTekade Fix the merge conflict. Also, refrain from changing the formatting or making so many lines of changes in one PR. Becomes difficult to review

**Comment by VinayakTekade** [comment]
@aravindvnair99 The conflicts have been fixed and the branch is ready to merge

**Pull request merged**
