### PR TITLE
Stage 2 of Frontend Fixes

### LINKED ISSUE #46: Major Fixes and Optimizations in Frontend
## Requirements to be fulfilled
- [x] Minor CSS fixes in all the page
- [x] Add Schedule
- [x] Remove Scrollbar in nav
- [x] Update links in Nav
- [x] Update Landing page for fest
- [x] Check Screen responsiveness
- [x] Text formatting in Schedule Page
- [x] Collapse on About Aykya page
- [x] Update favicon
- [x] Logo at the top corner of every page inside the main menu shows an error
- [x] In the schedule section, 'day 1' 'day 2' etc aren't aligned to the centre of the box
- [x] In the management Week section of past events, there's no need for a 'next event' button
- [x] Designations for the organizing team page - doesn't make sense to have 3 "team heads"
- [x] **Add to Schedule** Workshop on Technical and Management students by TEM IEEE CHAPTER - Sunday 10 to 1AM
- [x] In the "Contact Us" page, when you hover over Contact Us, it gets blackened
- [x] Looks better when the aykya logo is in the centre (at the top) of every page, as of now it looks like it is a bit to the left. 'buy tickets' button could either be a bit smaller or the words could come one below the other.
- [x] If i click on get tickets at bottom. It doesn't go to ACRD page.
- [x] Have to change the Campus Ambassador text (For mobile view). 
- [x] Remove unnecessary HTML

## Pending
- [ ] Refactor code
- [ ] Remove unnecessary CSS
- [ ] Remove unnecessary JS
- [ ] Check console for malfunctioning JS and rectify
- [ ] Remove unnecessary images

# Feel free to add to this list if you discover any bugs

### LINKED ISSUE #59: Redirect to homepage on click of AYKYA logo
When one clicks on AYKYA logo, it should redirect to the home page. Goes to 404 now.

### PR DESCRIPTION
**Pull request by VinayakTekade**
#46 

- Fixed index page link. Fixes #59 
- Commented schedule page for readability 
- Added new technical event
- Fixed Contact page heading gradient
- Updated text colours in about page
- Unified navbar across the website
- Added collapsible button in about page.
- Changed the font colours in about page.
- Re-positioned the images according to the text in about page.

### CODE REVIEW

**Review by aravindvnair99 — COMMENTED** [review]
Reviewed until 34383ef. LGTM so far. 👍

**Comment by VinayakTekade** [comment]
@aravindvnair99 Not sure what `AccessLint` is recommending. There's a label already present.

**Comment by VinayakTekade** [comment]
WIll work on remaining fixes of #46 in Stage 3.

**Comment by aravindvnair99** [comment]
> @aravindvnair99 Not sure what `AccessLint` is recommending. There are labels already present for both the checkboxes.

@VinayakTekade That's a bug. You can ignore it. Looks like we need to inform @accesslint about it.

**Review by aravindvnair99 — APPROVED** [review]

**Pull request merged**
