### PR TITLE
Added social links and Changed designations

### PR DESCRIPTION
**Pull request by suneel87**
Signed-off-by: Suneel Nadipalli <nsuneel89@gmail.com>

Fixes #
-Added links for all social media
-Removed "Head" from all designations
## Proposed Changes

-
-
-

### CODE REVIEW

**Review by aravindvnair99 — CHANGES_REQUESTED** [review]
@suneel87 Resend with only `members.ejs` and `footer.ejs`.

**Comment by suneel87** [comment]
@aravindvnair99 Do you want me to send a fresh PR by only changing members.ejs and footer.ejs ?

**Comment by aravindvnair99** [comment]
> @aravindvnair99 Do you want me to send a fresh PR by only changing members.ejs and footer.ejs ?

@suneel87 Yes, that's right

**Comment by suneel87** [comment]
@aravindvnair99  Ohk cool, I'll make a new branch and send it again, yeah?

**Pull request closed without merging**
