### PR TITLE
Landing page fix

### PR DESCRIPTION
**Pull request by Subaharish**
## Another Layout for Landing page after countdown goes null

### CODE REVIEW

**Review by aravindvnair99 — CHANGES_REQUESTED** [review]
@Subaharish Fix the issues listed [here](https://github.com/aravindvnair99/AYKYA-Fest/pull/81/checks?check_run_id=1279458900) by @code-factor.

**Comment by aravindvnair99** [comment]
@Subaharish Ready to be merged?

**Comment by aravindvnair99** [comment]
Seems like you made 6 to 9. Have a look at them

**Comment by Subaharish** [comment]
> Seems like you made 6 to 9. Have a look at them

Fixed code factor issues.

**Comment by Subaharish** [comment]
> @Subaharish Ready to be merged?

Yes, but its not responsive yet.

**Comment by Subaharish** [comment]
@aravindvnair99  Should I place it for review or let it in draft?

**Comment by aravindvnair99** [comment]
@Subaharish I'm merging for the time being as they want to review. You can send in another PR today.

CC: @VinayakTekade

**Review by aravindvnair99 — APPROVED** [review]

**Comment by aravindvnair99** [comment]
@Subaharish @VinayakTekade I have reverted this as there were a lot of bugs that were reported. Contact Lakshmi for the same.

**Pull request merged**
